### ISSUE TITLE
DNS Cache is not used when the type of the response record is CNAME

### ISSUE THREAD

**Issue by robjr** [reactphp/dns#119]
Hi guys, I'm making an X amount of asynchronous requests using the reactphp HttpClient and I noticed that for every single request it always tries to resolve the DNS, instead of using the cached version.

I saw that the connect method in the DnsConnector calls the resolve method of the [Resolver](https://github.com/reactphp/socket/blob/master/src/DnsConnector.php#L43). 
Then I used one of the code examples in the repo to test it and try to figure out why it doesn't use the cache. This code tries to resolve the same domain two times and while I am running I listen to the udp port 53 to see if there is an attempt of resolving the domain.
```
        $loop = \React\EventLoop\Factory::create();
        $config = Config::loadSystemConfigBlocking();
        $server = $config->nameservers ? reset($config->nameservers) : '8.8.8.8';
        $factory = new Factory();
        $resolver = $factory->createCached($server, $loop);
        $name = 'any.example.com';
        $resolver->resolve($name)->then(function ($ip) use ($name) {
            echo 'IP for ' . $name . ': ' . $ip . PHP_EOL;
        }, 'printf');
        
        $loop->addTimer(1.0, function() use ($name, $resolver) {
            $resolver->resolve($name)->then(function ($ip) use ($name) {
                echo 'IP for ' . $name . ': ' . $ip . PHP_EOL;
            }, 'printf');
        });
        $loop->run();
```

Let's suppose that the $name variable is equal to 'example.com' and we run the code above. It resolves the domain the first time and then the second time it gets from the cache as expected without making any call to the DNS server.

However, let's suppose that $name is equal to 'test.example.com'. It resolves the domain the first time when the resolve method in the code above is called, but when it is called for the second time, instead of getting the value from the cache, it resolves the same domain again.

One difference between the both examples is that in the first one, the DNS server responds with a record of type A (id 1) while in the second one it responds with type CNAME (id 5).

When the cache is saved, this type is used as part of the cache key generated [here](https://github.com/reactphp/dns/blob/75ae3286c03eb022a6fbf909e6148d5022588ba4/src/Query/RecordCache.php#L121). 

Having this in mind, let's try to run the first example with URL example.com. 

The resolve method is called, a cache lookup is done, no entry is found and then a request is done to the DNS server which responds with a TYPE A record. During the second call of the resolve method, a cache lookup is done and an entry with the key 'example.com:1:1' is found \o/

For the URL test.example.com, the resolve method is called, a cache lookup is done, no entry is found and the server responds with a TYPE CNAME record. The cache is then saved with the key: 'test.example.com:**5**:1'. During the second call, a cache lookup is done and it tries to look for the key 'test.example.com:**1**:1' because of the [default Message::TYPE_A](https://github.com/reactphp/dns/blob/75ae3286c03eb022a6fbf909e6148d5022588ba4/src/Resolver/Resolver.php#L23) in resolve method which is called on the DnsConnector. As a result, it does not find the cache and it calls the DNS server again.

One question I have is why do we need to specify the record type in the cache? is it possible to have such records coexisting 'example.com:5' and 'example.com:1'?

How could I continue making the assynchronous call with the client without resolving the same domain multiple times?
```
$loop = React\EventLoop\Factory::create();
$client = new Client($loop);
```

**Comment by rd4704** [comment]
+1
Very good explanation @robjr. I bumped into this issue as well and was puzzled with this for a while. Would love to get this issue fixed.

**Comment by WyriHaximus** [comment]
Hey @robjr and @rd4704 sorry for the late reply going through all my and react's open PR's and issues. We've discussed this internally and we haven't devised a fix for it yet. But I wanted to ensure you both we are aware of the issue and you feedback has been heared, @robjr thank you for the great summarisation :+1:
