### ISSUE TITLE
Gate way issue Discord

### ISSUE THREAD

**Issue by Sonus2021** [reactphp/dns#126]
9833a7395829bb4e2d56.js:108 WebSocket connection to 'wss://gateway.discord.gg/?encoding=etf&v=6&compress=zstd-stream' failed: Error during WebSocket handshake: Unexpected response code: 520 I need some help as soon as anone can

**Comment by clue** [comment]
This does not sound like an issue in this library. Feel free to update if you feel there's something that needs to be done here.
