### ISSUE TITLE
Ask host OS for DNS service address at startup, if none given by caller

### ISSUE THREAD

**Issue by bkidwell** [reactphp/dns#149]
Is it possible to fix `reactphp/dns` so that if you pass in `''` as the DNS service address, it puts resolution on hold and asks the host OS for the correct address to use, before performing any DNS queries?

I arrived here after finding Google's DNS address hard-coded in Phergie IRC framework... This rubs me the wrong way. 1) Google's DNS shouldn't be hard-coded in places like this. 2) Eventually someone's going to fail to setup a non-Internet private network service and wonder why can't lookup any local addresses.

It's fairly easy to do it with shell commands on Windows; here are some answers for doing it [from a Unix shell](https://unix.stackexchange.com/questions/28941/what-dns-servers-am-i-using)

**Comment by bkidwell** [comment]
Sorry. I didn't see this in the Readme and `examples` folder...

https://github.com/reactphp/dns/blob/master/examples/01-one.php

What I'm asking for has already been implemented, and Phergie needs to be fixed. I'll fix Phergie and submit a pull request there.

**Comment by clue** [comment]
Thanks for updating this ticket with your findings! It looks like this piece of code was added to Phergie before we've [added support](https://github.com/reactphp/dns/releases/tag/v0.4.13) for automatically detecting the system DNS resolver, so I agree it looks like Phergie could use an update :+1: 

Go for it? :shipit: 

https://github.com/phergie/phergie-irc-client-react/blob/b0d03f1e1ff34a2868f1f7d677786fdd1786b320/src/Client.php#L76

**Comment by bkidwell** [comment]
Pull request submitted. (Over [there](https://github.com/phergie/phergie-irc-client-react/pull/70).)
