### ISSUE TITLE
Support DNS over TCP/IP transport and retry truncated UDP responses

### ISSUE THREAD

**Issue by clue** [reactphp/dns#19]
Resolution via TCP transport should use the [react/socket-client component](https://github.com/reactphp/socket-client).

Fixes #11 and #13.

**Comment by clue** [comment]
Depends on https://github.com/reactphp/socket-client/issues/12 so that the socket-client component does not depend on a DNS `Resolver` instance again.

**Comment by clue** [comment]
Updated title now that the SocketClient component has been deprecated via https://github.com/reactphp/socket/issues/74

**Comment by clue** [comment]
This ticket is ready to be implemented in a future version :+1: 

For the reference: See also the updated [RFC 7766](https://tools.ietf.org/html/rfc7766) and the old [RFC 1035](https://tools.ietf.org/html/rfc1035)

**Comment by someniatko** [comment]
@clue Any estimates, please?

**Comment by clue** [comment]
As much as I'd like to commit to specific date, I can only say that we will get to this feature as soon as time permits.

If you want to sponsor this feature, feel free to reach out :+1:
