### ISSUE TITLE
Mark current version as stable / memory limit exceeded

### ISSUE THREAD

**Issue by Ashus** [reactphp/dns#190]
I stumbled upon a problem with TcpTransportExecutor causing any memory limit to exceed in PHP 8.0 when using a simple query over google's 8.8.8.8 DNS server effectively breaking my implementation of communicating over sockets.
However your commits from Dec 6 fixed this. Current version of that class in dev-master works fine and doesn't break anything.

It cascades through several projects up to my main project. Sadly, sometimes there is a requirement to have minimum-stability: **stable**.
Please can you tag a new version with the current fixes, so it is marked as stable in composer? Thank you.

**Comment by clue** [comment]
@Ashus Thank you, will get to releasing the next version as soon as time allows!

This has been fixed via #189 recently, in the meantime you may use the `dev-master` version (or downgrade to v1.4.0).

I believe this has been answered, so I'm closing this for now. Feel report back otherwise :+1:
