### ISSUE TITLE
Implement message body parsing for types

### ISSUE THREAD

**Issue by clue** [reactphp/dns#31]
Implement message body parsing for types other than A and CNAME: NS, SOA, PTR, MX, TXT, AAAA

**Comment by WyriHaximus** [comment]
Out of interest how would you chose when to get an A or an AAAA? Don't want to us try and use an AAAA record on an IPv4 only connection or vice versa. Not sure if this is the right place to discuss that but it seems to be the most relevant.

**Comment by clue** [comment]
> Out of interest how would you chose when to get an A or an AAAA?

This ticket mainly focuses on implementing an API that allows fetching A or AAAA records. Both can be useful even if you're not using a dual stack connection.

In a follow-up ticket we should address how users can select which type should be preferred by default. We may likely end up with an additional method to define that IPv6 is preferred over IPv4.
