### ISSUE TITLE
Add react/promise to composer.json

### ISSUE THREAD

**Issue by SamMousa** [reactphp/dns#40]
As far as I can tell this library requires promises, so it makes sense to list them as a requirement in `composer.json`

**Comment by clue** [comment]
Not sure what you're asking for, this is already a requirement? :)

https://github.com/reactphp/dns/blob/751b3129556e04944f164e3556a20ca6e201e459/composer.json#L10

**Comment by SamMousa** [comment]
Hmm, must have missed it... Sry!
