### ISSUE TITLE
Multiple dns servers

### ISSUE THREAD

**Issue by cdekok** [reactphp/dns#6]
It would be nice if it was possible to add multiple dns servers

**Comment by WyriHaximus** [comment]
@clue You think this would be hard to do? We could let two servers race and use the first answer.

Refs: https://github.com/beyondcode/laravel-websockets/pull/31#issuecomment-445748421 by @mpociot

**Comment by WyriHaximus** [comment]
> As such, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I guess we would be really happy to accept PRs +1

Might have a use case for it soon :sunglasses:
