### ISSUE TITLE
Bug in new version of socket

### ISSUE THREAD

**Issue by Rathil** [reactphp/dns#62]
Create composer.json
`{
  "require": {
    "react/dns": "0.4.8"
  }
}`

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 8 installs, 0 updates, 0 removals
  - Installing react/promise (v2.5.1): Downloading (100%)
  - Installing react/cache (v0.4.1): Downloading (100%)
  - Installing react/event-loop (v0.4.3): Downloading (100%)
  - Installing react/promise-timer (v1.1.1): Downloading (100%)
  - Installing evenement/evenement (v2.0.0): Downloading (100%)
  - Installing react/stream (v0.6.0): Downloading (100%)
  - Installing react/socket (v0.7.2): Downloading (100%)
  - Installing react/dns (v0.4.8): Downloading (100%)
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
Writing lock file
Generating autoload files

Copy `vendor/react/dns/examples/01-one.php` to `test.php` and change:
`require __DIR__ . '/../vendor/autoload.php';`
to
`require 'vendor/autoload.php';`

$ php test.php
IP for www.google.com: 173.194.113.211

After that change `composer.json` to:
``{
  "require": {
    "react/dns": "0.4.9"
  }
}``

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating react/stream (v0.6.0 => v0.7.0): Downloading (100%)
  - Updating react/dns (v0.4.8 => v0.4.9): Downloading (100%)
  - Updating react/socket (v0.7.2 => v0.8.0): Downloading (100%)
Writing lock file
Generating autoload files

And run:

$ php test.php

React\Promise\Timer\TimeoutException: Timed out after 5 seconds in /tmp/test/vendor/react/promise-timer/src/functions.php:21
Stack trace:
// ...

**Comment by Rathil** [comment]
This is due to changes in the `react/socket`

**Comment by WyriHaximus** [comment]
Which OS is this on?

**Comment by Rathil** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by Rathil** [comment]
$ php -v
PHP 7.0.15-1+deb.sury.org~trusty+1 (cli) (built: Jan 20 2017 09:16:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.14-2+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

**Comment by clue** [comment]
Hi @Rathil! I've just verified that running the examples from this repo does work as expected, so I'm currently unable to reproduce this locally. May I ask you to provide a simple gist on how to reproduce this? Thanks!

FWIW, here's the output on my system:

```bash
$ cd workspace/reactphp-dns
$ COMPOSER_ROOT_VERSION=`git describe --abbrev=0` composer update
…

$ composer show react/*
react/cache         v0.4.1 Async caching.
react/event-loop    v0.4.3 Event loop abstraction layer that libraries can use for evented I/O.
react/promise       v2.5.1 A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer v1.1.1 Trivial timeout implementation for Promises
react/socket        v0.8.0 Async, streaming plaintext TCP/IP and secure TLS socket server and client connections for ReactPHP
react/stream        v0.7.0 Event-driven readable and writable streams for non-blocking I/O in ReactPHP

$ php examples/01-one.php 
IP for www.google.com: 172.217.17.68
```

**Comment by Rathil** [comment]
You will repeat the way I described it.
It is to copy and execute.

**Comment by Rathil** [comment]
composer show does not show what exactly you have installed, and what is available packages.

**Comment by WyriHaximus** [comment]
> You will repeat the way I described it.
> It is to copy and execute.

Just did that and it works fine for me.

`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

`php -v`:
```
PHP 7.1.4-1+deb.sury.org~trusty+1 (cli) (built: Apr 11 2017 22:45:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.4-1+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.16.2~linux-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.
```

**Comment by Rathil** [comment]
I tried it on another server and it all works.
Apparently this is a some problem I have with a working computer...
