### ISSUE TITLE
Why is $nameserver part of Resolver?

### ISSUE THREAD

**Issue by kelunik** [reactphp/dns#64]
`$nameserver` in `Resolver` is only ever passed to the `ExecutorInterface` instance, as such it should probably just be the job of the `ExecutorInterface` instance to know the nameserver. This allows implementing other executors getting their nameservers from the system's config for example.

**Comment by clue** [comment]
I'm not opposed to this, do you feel like filing a PR? :+1: 

I think both ways may have their pros and cons and I have no immediate plans to builds this from my end (no demand at the moment and more important issues), but I suppose we would be really happy to accept PRs and see how this works out :+1:
