### ISSUE TITLE
Consider implementing random case to increase message entropy (0x20 hack)

### ISSUE THREAD

**Issue by clue** [reactphp/dns#91]
Implementing random case for outgoing DNS queries can help improve message entropy and significantly reduce the risk for DNS poisoning attacks for certain scenarios.

Links for the reference:

* https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00
* https://serverfault.com/questions/759934/can-dns-response-answers-be-in-a-different-case-than-the-query
* https://serverfault.com/questions/261341/is-the-hostname-case-sensitive

This is particularly relevant for UDP queries (the default) and may be less so for in-flight messages over connection oriented protocols (#19 and #80).

I'm not working on this at the moment, but figured it's worth posting this here anyway. In case anybody feels like picking this up, PRs would be much appreciated 👍

**Comment by kelunik** [comment]
Consider using a CSPRNG as a first counter-measure first, PR already exists in https://github.com/reactphp/dns/pull/65.

**Comment by clue** [comment]
@kelunik I agree and have no use for this beyond the CSPRNG that has been implemented via #101, so I believe this has been answered and will close this for now :+1:
